一、資料讀取與套件載入

In [1]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense

In [2]:
train_data=pd.read_csv("Adult_FinalTrain.csv")
train_data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,5,77516,9,13,4,0,1,4,1,2174,0,40,38,0
1,50,4,83311,9,13,2,3,0,4,1,0,0,13,38,0
2,38,2,215646,11,9,0,5,1,4,1,0,0,40,38,0
3,53,2,234721,1,7,2,5,0,2,1,0,0,40,38,0
4,28,2,338409,9,13,2,9,5,2,0,0,0,40,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30157,27,2,257302,7,12,2,12,5,4,0,0,0,38,38,0
30158,40,2,154374,11,9,2,6,0,4,1,0,0,40,38,1
30159,58,2,151910,11,9,6,0,4,4,0,0,0,40,38,0
30160,22,2,201490,11,9,4,0,3,4,1,0,0,20,38,0
30161,52,3,287927,11,9,2,3,5,4,0,15024,0,40,38,1

In [3]:
test_data=pd.read_csv("Adult_FinalTest.csv")
test_data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,25,2,226802,1,7,4,6,3,2,1,0,0,40,37,0
1,38,2,89814,11,9,2,4,0,4,1,0,0,50,37,0
2,28,1,336951,7,12,2,10,0,4,1,0,0,40,37,1
3,44,2,160323,15,10,2,6,0,2,1,7688,0,40,37,1
4,34,2,198693,0,6,4,7,1,4,1,0,0,30,37,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15055,33,2,245211,9,13,4,9,3,4,1,0,0,40,37,0
15056,39,2,215419,9,13,0,9,1,4,0,0,0,36,37,0
15057,38,2,374983,9,13,2,9,0,4,1,0,0,50,37,0
15058,44,2,83891,9,13,0,0,3,1,1,5455,0,40,37,0
15059,35,3,182148,9,13,2,3,0,4,1,0,0,60,37,1

二、正規化與資料結構整理

In [4]:
train_mean=train_data.mean(axis=0)

In [5]:
train_std=train_data.std(axis=0)

In [6]:
test_mean=test_data.mean(axis=0)

In [7]:
test_std=test_data.std(axis=0)

In [8]:
train_data-=train_mean
train_data/=train_std
train_data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,0.042795,2.935952,-1.062704,-0.349859,1.128900,0.947831,-1.479030,-0.261245,0.385042,0.692795,0.146090,-0.218582,-0.077733,0.264920,-0.575682
1,0.880274,1.887651,-1.007855,-0.349859,1.128900,-0.387268,-0.734533,-0.885722,0.385042,0.692795,-0.147442,-0.218582,-2.331492,0.264920,-0.575682
2,-0.033339,-0.208951,0.244689,0.174760,-0.439731,-1.722368,-0.238202,-0.261245,0.385042,0.692795,-0.147442,-0.218582,-0.077733,0.264920,-0.575682
3,1.108677,-0.208951,0.425233,-2.448334,-1.224046,-0.387268,-0.238202,-0.885722,-2.011002,0.692795,-0.147442,-0.218582,-0.077733,0.264920,-0.575682
4,-0.794684,-0.208951,1.406635,-0.349859,1.128900,-0.387268,0.754461,2.236666,-2.011002,-1.443381,-0.147442,-0.218582,-0.077733,-5.303946,-0.575682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30157,-0.870818,-0.208951,0.638961,-0.874478,0.736742,-0.387268,1.498958,2.236666,0.385042,-1.443381,-0.147442,-0.218582,-0.244678,0.264920,-0.575682
30158,0.118929,-0.208951,-0.335247,0.174760,-0.439731,-0.387268,0.009964,-0.885722,0.385042,0.692795,-0.147442,-0.218582,-0.077733,0.264920,1.737013
30159,1.489349,-0.208951,-0.358569,0.174760,-0.439731,2.282931,-1.479030,1.612188,0.385042,-1.443381,-0.147442,-0.218582,-0.077733,0.264920,-0.575682
30160,-1.251490,-0.208951,0.110704,0.174760,-0.439731,0.947831,-1.479030,0.987711,0.385042,0.692795,-0.147442,-0.218582,-1.747184,0.264920,-0.575682
30161,1.032542,0.839350,0.928825,0.174760,-0.439731,-0.387268,-0.734533,2.236666,0.385042,-1.443381,1.881088,-0.218582,-0.077733,0.264920,1.737013

In [9]:
test_data-=test_mean
test_data/=test_std
test_data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,-1.028971,-0.222340,0.352087,-2.423358,-1.216522,0.933156,0.002725,1.006074,-2.034322,0.695809,-0.145434,-0.219162,-0.078886,0.260572,-0.570686
1,-0.057421,-0.222340,-0.944964,0.190166,-0.434884,-0.395450,-0.494773,-0.881961,0.382218,0.695809,-0.145434,-0.219162,0.750106,0.260572,-0.570686
2,-0.804767,-1.257085,1.395016,-0.855244,0.737574,-0.395450,0.997722,-0.881961,0.382218,0.695809,-0.145434,-0.219162,-0.078886,0.260572,1.752160
3,0.390987,-0.222340,-0.277360,1.235576,-0.044064,-0.395450,0.002725,-0.881961,-2.034322,0.695809,0.852596,-0.219162,-0.078886,0.260572,1.752160
4,-0.356359,-0.222340,0.085941,-2.684711,-1.607342,0.933156,0.251475,-0.252616,0.382218,0.695809,-0.145434,-0.219162,-0.907879,0.260572,-0.570686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15055,-0.431094,-0.222340,0.526389,-0.332539,1.128393,0.933156,0.748973,1.006074,0.382218,0.695809,-0.145434,-0.219162,-0.078886,0.260572,-0.570686
15056,0.017314,-0.222340,0.244308,-0.332539,1.128393,-1.724057,0.748973,-0.252616,0.382218,-1.437080,-0.145434,-0.219162,-0.410484,0.260572,-0.570686
15057,-0.057421,-0.222340,1.755116,-0.332539,1.128393,-0.395450,0.748973,-0.881961,0.382218,0.695809,-0.145434,-0.219162,0.750106,0.260572,-0.570686
15058,0.390987,-0.222340,-1.001045,-0.332539,1.128393,-1.724057,-1.489770,1.006074,-3.242591,0.695809,0.562715,-0.219162,-0.078886,0.260572,-0.570686
15059,-0.281625,0.812405,-0.070713,-0.332539,1.128393,-0.395450,-0.743522,-0.881961,0.382218,0.695809,-0.145434,-0.219162,1.579099,0.260572,1.752160

In [10]:
train_predict=train_data.drop(columns=['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship'
                      ,'race','sex','capital-gain','capital-loss','native-country','salary'],axis=1)
train_predict

       hours-per-week
0           -0.077733
1           -2.331492
2           -0.077733
3           -0.077733
4           -0.077733
...               ...
30157       -0.244678
30158       -0.077733
30159       -0.077733
30160       -1.747184
30161       -0.077733

[30162 rows x 1 columns]

In [11]:
test_predict=test_data.drop(columns=['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship'
                      ,'race','sex','capital-gain','capital-loss','native-country','salary'],axis=1)
test_predict

       hours-per-week
0           -0.078886
1            0.750106
2           -0.078886
3           -0.078886
4           -0.907879
...               ...
15055       -0.078886
15056       -0.410484
15057        0.750106
15058       -0.078886
15059        1.579099

[15060 rows x 1 columns]

三、建立前饋神經網路模型

In [12]:
model1=Sequential()
model1.add(Dense(1000,activation='relu',input_shape=(train_data.shape[1],)))
model1.add(Dense(100,activation='relu'))
model1.add(Dense(100,activation='relu'))
model1.add(Dense(100,activation='relu'))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss="mse", optimizer="adam",metrics=["mae"])

In [13]:
model2=Sequential()
model2.add(Dense(1000,activation='relu',input_shape=(train_data.shape[1],)))
model2.add(Dense(100,activation='relu'))
model1.add(Dense(100,activation='relu'))
model1.add(Dense(100,activation='relu'))
model2.add(Dense(1,activation='sigmoid'))
model2.compile(loss="mse", optimizer="rmsprop",metrics=["mape"])

In [14]:
model3=Sequential()
model3.add(Dense(1000,activation='relu',input_shape=(train_data.shape[1],)))
model3.add(Dense(100,activation='relu'))
model1.add(Dense(100,activation='relu'))
model1.add(Dense(100,activation='relu'))
model3.add(Dense(1,activation='sigmoid'))
model3.compile(loss="mse", optimizer="adam",metrics=["mse"])

四、資料匯入模型訓練

In [15]:
model1.fit(train_data,train_predict,epochs=20,batch_size=20)

Epoch 1/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6382 - mae: 0.4379
Epoch 2/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6300 - mae: 0.4188
Epoch 3/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6293 - mae: 0.4145
Epoch 4/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6292 - mae: 0.4137
Epoch 5/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6291 - mae: 0.4130
Epoch 6/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6290 - mae: 0.4121
Epoch 7/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6290 - mae: 0.4122
Epoch 8/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mae: 0.4109
Epoch 9/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6290 - mae: 0.4113
Epoch 10/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mae: 0.4109
Epoch 11/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mae: 0.4108
Epoch 12/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6290 - mae: 0.4113
Epoch 13/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mae: 0.4107
Epoch 14/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mae: 0.4108
Epoch 15/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mae: 0.4107A: 0s - loss: 0.6385 -
Epoch 16/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mae: 0.4106
Epoch 17/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mae: 0.4104
Epoch 18/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mae: 0.4102
Epoch 19/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mae: 0.4104
Epoch 20/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mae: 0.4099

In [16]:
model2.fit(train_data,train_predict,epochs=20,batch_size=20)

Epoch 1/20
1509/1509 [==============================] - 4s 3ms/step - loss: 0.6343 - mape: 82.1227
Epoch 2/20
1509/1509 [==============================] - 4s 3ms/step - loss: 0.6293 - mape: 75.6237
Epoch 3/20
1509/1509 [==============================] - 7s 5ms/step - loss: 0.6291 - mape: 75.1030
Epoch 4/20
1509/1509 [==============================] - 6s 4ms/step - loss: 0.6290 - mape: 74.8342
Epoch 5/20
1509/1509 [==============================] - 5s 4ms/step - loss: 0.6290 - mape: 74.7455
Epoch 6/20
1509/1509 [==============================] - 5s 3ms/step - loss: 0.6290 - mape: 74.6262
Epoch 7/20
1509/1509 [==============================] - 5s 4ms/step - loss: 0.6290 - mape: 74.5851
Epoch 8/20
1509/1509 [==============================] - 5s 3ms/step - loss: 0.6289 - mape: 74.5698
Epoch 9/20
1509/1509 [==============================] - 3s 2ms/step - loss: 0.6289 - mape: 74.4825
Epoch 10/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mape: 74.4595A: 0s - loss: 0.6322 - mape: 74.5
Epoch 11/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mape: 74.4328
Epoch 12/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mape: 74.4274
Epoch 13/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mape: 74.3875
Epoch 14/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mape: 74.3626
Epoch 15/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mape: 74.3832
Epoch 16/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mape: 74.3457
Epoch 17/20
1509/1509 [==============================] - 3s 2ms/step - loss: 0.6289 - mape: 74.3725
Epoch 18/20
1509/1509 [==============================] - 4s 2ms/step - loss: 0.6289 - mape: 74.3230
Epoch 19/20
1509/1509 [==============================] - 5s 3ms/step - loss: 0.6289 - mape: 74.3272
Epoch 20/20
1509/1509 [==============================] - 6s 4ms/step - loss: 0.6289 - mape: 74.3083

In [17]:
model3.fit(train_data,train_predict,epochs=20,batch_size=20)

Epoch 1/20
1509/1509 [==============================] - 5s 3ms/step - loss: 0.6370 - mse: 0.6370
Epoch 2/20
1509/1509 [==============================] - 4s 3ms/step - loss: 0.6305 - mse: 0.6305
Epoch 3/20
1509/1509 [==============================] - 4s 3ms/step - loss: 0.6298 - mse: 0.6298
Epoch 4/20
1509/1509 [==============================] - 4s 3ms/step - loss: 0.6293 - mse: 0.6293
Epoch 5/20
1509/1509 [==============================] - 4s 2ms/step - loss: 0.6291 - mse: 0.6291
Epoch 6/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6290 - mse: 0.6290
Epoch 7/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6290 - mse: 0.6290
Epoch 8/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6290 - mse: 0.6290
Epoch 9/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mse: 0.6289
Epoch 10/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6290 - mse: 0.6290
Epoch 11/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mse: 0.6289
Epoch 12/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6290 - mse: 0.6290
Epoch 13/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mse: 0.6289
Epoch 14/20
1509/1509 [==============================] - 2s 1ms/step - loss: 0.6289 - mse: 0.6289
Epoch 15/20
1509/1509 [==============================] - 3s 2ms/step - loss: 0.6289 - mse: 0.6289A: 0s - loss: 0.6255 - mse: 0.
Epoch 16/20
1509/1509 [==============================] - 3s 2ms/step - loss: 0.6289 - mse: 0.6289
Epoch 17/20
1509/1509 [==============================] - 5s 3ms/step - loss: 0.6289 - mse: 0.6289
Epoch 18/20
1509/1509 [==============================] - 6s 4ms/step - loss: 0.6289 - mse: 0.6289
Epoch 19/20
1509/1509 [==============================] - 5s 4ms/step - loss: 0.6289 - mse: 0.6289
Epoch 20/20
1509/1509 [==============================] - 6s 4ms/step - loss: 0.6289 - mse: 0.6289

五、績效評估

In [18]:
loss,mae_score= model1.evaluate(test_data,test_predict)         
print("lose= {:.2f}".format(loss))
print("mae= {:.2f}".format(mae_score))

471/471 [==============================] - 1s 2ms/step - loss: 0.6295 - mae: 0.4093
lose= 0.63
mae= 0.41

In [19]:
loss,mape_score= model2.evaluate(test_data,test_predict)         
print("lose= {:.2f}".format(loss))
print("mape= {:.2f}".format(mape_score))

471/471 [==============================] - 1s 2ms/step - loss: 0.6296 - mape: 74.8723
lose= 0.63
mape= 74.87

In [20]:
loss,mse_score= model3.evaluate(test_data,test_predict)         
print("lose= {:.2f}".format(loss))
print("mse= {:.2f}".format(mse_score))

471/471 [==============================] - 1s 2ms/step - loss: 0.6296 - mse: 0.6296
lose= 0.63
mse= 0.63